# Generated by Django 4.2.1 on 2023-05-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=225)),
                ("positions", models.CharField(max_length=225)),
                ("industry", models.CharField(max_length=225)),
                ("company_name", models.CharField(max_length=255)),
                ("submit_before", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="")),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=225)),
                ("componay_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.EmailField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=125)),
                ("address_city", models.CharField(max_length=125)),
                ("email_address", models.EmailField(max_length=225)),
                ("post_address", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=125)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TZ", "NECTA School"),
                            ("UK", "Cambridge International School"),
                            ("IB", "International Baccalaureate® (IB)"),
                        ],
                        max_length=255,
                    ),
                ),
                ("company_sizes", models.IntegerField()),
                ("description", models.TextField()),
                ("thumbnail", models.ImageField(default="default.png", upload_to="")),
                ("website_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
            ],
        ),
    ]
