# Generated by Django 4.2.1 on 2023-05-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=125)),
                ("address_region", models.CharField(max_length=125)),
                ("address_city", models.CharField(max_length=125)),
                ("post_address", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=125)),
                ("category", models.CharField(max_length=255)),
                ("company_sizes", models.IntegerField()),
                ("benefits", models.CharField(max_length=225)),
                ("description", models.TextField()),
                ("twitter_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
            ],
        ),
    ]
