# Generated by Django 4.2.1 on 2023-06-04 14:01

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=225)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Full Time", "Full Time"),
                            ("Part Time", "Part Time"),
                            ("Intenship", "Intenship"),
                        ],
                        max_length=225,
                    ),
                ),
                ("posted_on", models.DateTimeField(auto_now_add=True)),
                ("company_summary", models.TextField()),
                ("industry", models.CharField(max_length=225)),
                ("company_name", models.CharField(max_length=255)),
                ("submit_before", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="")),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                ("location", models.CharField(max_length=225)),
                ("componay_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["-posted_on"],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.EmailField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=125)),
                ("address_city", models.CharField(max_length=125)),
                ("email_address", models.EmailField(max_length=225)),
                ("post_address", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=125)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NECTA School", "NECTA School"),
                            (
                                "Cambridge International School",
                                "Cambridge International School",
                            ),
                            (
                                "International Baccalaureate® (IB)",
                                "International Baccalaureate® (IB)",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("company_sizes", models.IntegerField()),
                ("description", models.TextField()),
                ("thumbnail", models.ImageField(default="default.png", upload_to="")),
                ("school_logo", models.ImageField(default="default.png", upload_to="")),
                ("website_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
            ],
        ),
    ]
