# Generated by Django 4.2.1 on 2023-06-06 14:54

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=225)),
                (
                    "blog_category",
                    models.CharField(
                        choices=[
                            ("Curriculum Planning", "Curriculum Planning"),
                            ("Communication Skills", "Communication Skills"),
                            (
                                "Differentiated Instruction",
                                "Differentiated Instruction",
                            ),
                            ("Formative Assessment", "Formative Assessment"),
                            ("Mental Health", "Mental Health"),
                            ("New Teachers", "New Teachers"),
                            ("STEM", "STEM"),
                            ("Student Engagement", "Student Engagement"),
                            ("Teacher Collaboration", "Teacher Collaboration"),
                            ("Teaching Strategies", "Teaching Strategies"),
                            ("Technology Integration", "Technology Integration"),
                        ],
                        max_length=225,
                    ),
                ),
                ("blog_intro", models.TextField()),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                ("thumbnail", models.ImageField(upload_to="")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
        migrations.AlterField(
            model_name="job",
            name="industry",
            field=models.CharField(
                choices=[
                    ("Advertising and Marketing", "Advertising and Marketing"),
                    (" Aerospace", " Aerospace"),
                    ("Agriculture", "Agriculture"),
                    ("Computer and Technology", "Computer and Technology"),
                    ("Construction", "Construction"),
                    ("Education", "Education"),
                    ("Energy", "Energy"),
                    ("Entertainment", "Entertainment"),
                    (" Fashion", " Fashion"),
                    ("Finance and Economic", "Finance and Economic"),
                    ("Food and Beverage", "Food and Beverage"),
                    ("Health care", "Health care"),
                    ("Hospitality", "Hospitality"),
                    ("Manufacturing", "Manufacturing"),
                    ("Media and news", "Media and news"),
                    ("Mining", "Mining"),
                    ("Pharmaceutical", "Pharmaceutical"),
                    ("Telecommunication", "Telecommunication"),
                    ("Transportation", "Transportation"),
                ],
                max_length=225,
            ),
        ),
    ]
