# Generated by Django 4.2.1 on 2023-05-23 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[("FT", "Full Time"), ("PT", "Part Time"), ("IN", "Intenship")],
                default="",
                max_length=225,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="posted_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
