# Generated by Django 4.2.1 on 2023-05-16 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0002_alter_school_benefits_alter_school_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="benefits",
        ),
    ]
