# Generated by Django 4.2 on 2023-05-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0002_job_job_type_job_posted_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("Full Time", "Full Time"),
                    ("Part Time", "Part Time"),
                    ("Intenship", "Intenship"),
                ],
                max_length=225,
            ),
        ),
    ]
