# Generated by Django 4.2.1 on 2023-06-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0002_blog_alter_job_industry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_title", models.CharField(max_length=255)),
                ("event_date", models.CharField(max_length=255)),
                ("event_time", models.CharField(max_length=255)),
                ("event_location", models.CharField(max_length=255)),
                ("event_speaker", models.CharField(max_length=255)),
                ("speaker_occupation", models.CharField(max_length=255)),
                ("speaker_description", models.TextField()),
                ("event_description", models.TextField()),
            ],
        ),
    ]
