# Generated by Django 4.2.1 on 2023-06-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0003_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="speaker_thumbnail",
            field=models.ImageField(default="default.png", upload_to=""),
        ),
    ]
