# Generated by Django 4.2 on 2023-05-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0003_alter_job_job_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-posted_on"]},
        ),
        migrations.AlterField(
            model_name="school",
            name="category",
            field=models.CharField(
                choices=[
                    ("NECTA School", "NECTA School"),
                    (
                        "Cambridge International School",
                        "Cambridge International School",
                    ),
                    (
                        "International Baccalaureate® (IB)",
                        "International Baccalaureate® (IB)",
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
