# Generated by Django 4.2.1 on 2023-05-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0004_remove_school_address_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="website_url",
            field=models.URLField(blank=True),
        ),
    ]
