# Generated by Django 4.2.1 on 2023-06-12 08:22

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0004_event_speaker_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
