# Generated by Django 4.2.1 on 2023-05-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0005_school_website_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="email_address",
            field=models.EmailField(default="", max_length=225),
            preserve_default=False,
        ),
    ]
