# Generated by Django 4.2.1 on 2023-05-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0006_school_email_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=225)),
            ],
        ),
    ]
