# Generated by Django 4.2.1 on 2023-05-18 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0007_newsletter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsletter",
            old_name="email",
            new_name="email_address",
        ),
    ]
