# Generated by Django 4.2 on 2023-05-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0008_rename_email_newsletter_email_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="thumbnail",
            field=models.ImageField(default="default.png", upload_to=""),
        ),
    ]
